name: furlong
version: 1.0.0-dev
description: SQLJocky migration tool.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/furlong
dependencies:
  sqljocky: ">=0.14.1 <1.0.0"
dev_dependencies:
  http: ">= 0.11.3 < 0.12.0"
  test: ">= 0.12.13 < 0.13.0"